# Generated by Django 3.0.3 on 2020-09-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_ID', models.AutoField(primary_key=True, serialize=False)),
                ('login_Name', models.CharField(max_length=30)),
                ('login_Password', models.CharField(max_length=12)),
                ('login_Rank', models.CharField(max_length=15)),
            ],
        ),
    ]
