# Generated by Django 3.0.3 on 2020-09-09 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table='Login',
        ),
    ]
