# Generated by Django 3.0.3 on 2020-09-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malipo', '0002_auto_20200909_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finger_Print',
            fields=[
                ('finger_Print_ID', models.AutoField(primary_key=True, serialize=False)),
                ('finger_Print_Desc', models.CharField(max_length=60)),
                ('finger_Print_Image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Finger_Print',
            },
        ),
    ]
