# Generated by Django 3.0.3 on 2020-09-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malipo', '0003_finger_print'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_ID', models.AutoField(primary_key=True, serialize=False)),
                ('department_Name', models.CharField(max_length=60)),
                ('department_Desc', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
    ]
