# Generated by Django 3.0.3 on 2020-09-28 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malipo', '0004_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_ID', models.AutoField(primary_key=True, serialize=False)),
                ('employee_Name', models.CharField(max_length=56)),
                ('employee_Email', models.EmailField(max_length=254)),
                ('employee_PhoneNumber', models.IntegerField()),
                ('employee_department_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malipo.Department')),
                ('employee_finger_Print_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malipo.Finger_Print')),
                ('employee_login_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malipo.Login')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
