# Generated by Django 3.0.3 on 2020-10-02 03:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malipo', '0006_leavetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetable',
            name='leave_Start_Date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('timeslot_ID', models.AutoField(primary_key=True, serialize=False)),
                ('timeslot_Check_In_Time', models.TimeField(default=datetime.datetime(2020, 10, 2, 6, 17, 11, 670703))),
                ('timeslot_Check_Out_Time', models.TimeField()),
                ('timeslot_employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malipo.Employee')),
            ],
            options={
                'db_table': 'Timeslot',
            },
        ),
    ]
