# Generated by Django 3.0.3 on 2020-10-02 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malipo', '0007_auto_20201002_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='timeslot_Check_In_Time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 2, 6, 19, 6, 523287)),
        ),
    ]
